export const LOAD_CATEGORY_NAMES = 'app/Navbar/LOAD_CATEGORY_NAMES';
export const LOAD_CATEGORY_NAMES_SUCCESS =
  'app/Navbar/LOAD_CATEGORY_NAMES_SUCCESS';
export const LOAD_CATEGORY_NAMES_ERROR = 'app/Navbar/LOAD_CATEGORY_NAMES_ERROR';
